spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/Automotive_System
    username: postgres
    password: postgres
    pool:
      enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.example.demo: DEBUG