#spring:
#  application:
#    name: customer-service
#  datasource:
#    url: jdbc:postgresql://localhost:5433/customers
#    username: postgres
#    password: toor
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: customer-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/customers
    username: postgres
    password: toor

